version: '2'
services:
    frontdesk2-app:
        image: frontdesk2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://frontdesk2-mysql:3306/frontdesk2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://frontdesk2-elasticsearch:9200
        ports:
            - 8080:8080
    frontdesk2-mysql:
        extends:
            file: mysql.yml
            service: frontdesk2-mysql
    frontdesk2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: frontdesk2-elasticsearch
